#!/bin/bash

# The pre_start_cartridge and pre_stop_cartridge hooks are *SOURCED*
# immediately before (re)starting or stopping the specified cartridge.
# They are able to make any desired environment variable changes as
# well as other adjustments to the application environment.

# The post_start_cartridge and post_stop_cartridge hooks are executed
# immediately after (re)starting or stopping the specified cartridge.

# Exercise caution when adding commands to these hooks.  They can
# prevent your application from stopping cleanly or starting at all.
# Application start and stop is subject to different timeouts
# throughout the system.

if [ -f "$OPENSHIFT_REPO_DIR/.openshift/lib/utils" ]; then
   source "$OPENSHIFT_REPO_DIR/.openshift/lib/utils"
   ensure_node_is_installed
   setup_path_for_custom_node_version
fi

if [ "x$OPENSHIFT_MONGODB_DB_PASSWORD" != "x" ]
then
  password=$OPENSHIFT_MONGODB_DB_PASSWORD
  echo "use admin
      db.auth(\"admin\", \"${password}\")
      db.system.users.find()
      use ${OPENSHIFT_APP_NAME}-events
      db.addUser(\"admin\", \"${password}\")
      use ${OPENSHIFT_APP_NAME}-metrics
      db.addUser(\"admin\", \"${password}\")
      exit
     "  | mongo --host $OPENSHIFT_MONGODB_DB_HOST --port $OPENSHIFT_MONGODB_DB_PORT -u $OPENSHIFT_MONGODB_DB_USERNAME -p $OPENSHIFT_MONGODB_DB_PASSWORD ${OPENSHIFT_APP_NAME}
fi

## init database if needed
cd "${OPENSHIFT_REPO_DIR}/admin/api/init"
NODE_ENV=openshift node initDashboards.js
