#!/bin/bash -e
# This is a simple post deploy hook executed after your application
# is deployed and started.  This script gets executed directly, so
# it could be python, php, ruby, etc.

source $OPENSHIFT_CARTRIDGE_SDK_BASH

